
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        #命名空间
        namespace: c25ca3f9-9907-468b-ae73-2da5a7daa0e8
        #分组
        group: DEFAULT_GROUP
        #集群名
        cluster-name: WH
        server-addr: 192.168.1.2:8848
        #是否持久实例
        ephemeral: false
        username: nacos
        password: nacos


server:
  port: 7080
