
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        #命名空间
        namespace: test
        #分组
        group: default
        #集群名
        cluster-name: SH
        server-addr: 192.168.1.2:8848
        #是否持久实例
        ephemeral: false
        username: nacos
        password: nacos



server:
  port: 7081
